### ISSUE TITLE
大概知道怎么还原了

### ISSUE THREAD

**Issue by s120900225** [28598519a/AGUDecoder#1]
首先是按照大佬的工具解开全部文件后找到resData文件并且让其余文件变回第一行
然后在文本里面找到
assets/resources/config.json	res/SdINvL/IkbgDzR/ry8i/p5P0TnqZzCXbRvK.json
重点是config.json，然后在根据里面的内容进行第二次整理就可以了。

**Comment by 28598519a** [comment]
config.json不就是我在readme已經說的嗎?

主要問題在於config.json裡的那些路徑跟resData第一行的關係，我不知道怎麼對照
